sonar.projectKey=Yatarox_mspr_TPRE612
sonar.organization=yatarox
sonar.python.version=3.11

sonar.sources=api/src
sonar.tests=api/tests
sonar.test.inclusions=api/tests/**/*.py
sonar.python.coverage.reportPaths=api/coverage.xml