sonar.projectKey=Yatarox_mspr_TPRE612_etl
sonar.organization=yatarox
sonar.python.version=3.11

sonar.sources=etl/scripts
sonar.tests=etl/scripts
sonar.test.inclusions=etl/scripts/**/tests/**/*.py,etl/scripts/**/test_*.py
sonar.python.coverage.reportPaths=etl/coverage.xml