name: Build All Services

on:
  push:
    branches: [main, ETL, api, dashboard, database]
  pull_request:
    branches: [main]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, dashboard, database, datascience, etl]
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.service }}
        run: docker build -t ${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}