name: API Build Only

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r ./api/requirements.txt
      - name: Check dependencies for vulnerabilities
        run: |
          pip install pip-audit
          pip-audit -r ./api/requirements.txt
      - name: Build Docker image
        run: |
          docker build -t mspr-api ./api
      - name: Run tests
        run: |
          docker run --rm mspr-api pytest -v